[Sonic Frontiers] Implemented basic code library support for PlayerVisuals
hedge-dev/HMMCodes pull request #60
Opened 2023-11-17 22:22 UTC by NM-20

2023-11-17 22:57 UTC, HyperBE32 requested changes

2023-11-17 22:57 UTC, HyperBE32 commented on Source/Sonic Frontiers/Libraries/GOComponents.hmm
> +        FUNCTION_PTR(PlayerVisual.Data *, fpInternalGetVisualAs, _sigInternalGetVisualAs, GOCPlayerVisual *_this, uint in_nameHash)
Please do `type* name`, rather than `type *name`.

2023-11-17 22:57 UTC, HyperBE32 commented on Source/Sonic Frontiers/Libraries/GOComponents.hmm
> +        public T *GetVisualAs<T>() where T : unmanaged
Rename to `GetVisual` and create a separate implementation that returns `PlayerVisual.Data*` with an argument for the name of the visual, using the `MAKE_GENERIC_API` macro for the templated version.

For example;
```cs
public PlayerVisual.Data* GetVisual(string in_visualName)
{
    fixed (GOCPlayerVisual* pThis = &this)
    {
        return GET_FUNCTION_PTR(fpInternalGetVisualAs)(pThis, StringMapOperation.ComputeHash(in_visualName));
    }
}

MAKE_GENERIC_API(GetVisual)
```

The fact that this function pointer exists also suggests this class likely contains a `MoveArray` of some kind, so it might be worth mapping that instead, but I'll allow it for this PR.

2023-11-17 22:57 UTC, HyperBE32 commented on Source/Sonic Frontiers/Libraries/PlayerVisual.hmm
> +        [FieldOffset(0x118)] public bool              IsSuperSonic2;
Remove the padding for this member.

2023-11-17 22:57 UTC, HyperBE32 commented on Source/Sonic Frontiers/Libraries/GOComponents.hmm
> +        [FieldOffset(0x000)] public GOComponent        Base;
Remove the padding for this member.

2023-11-17 22:57 UTC, HyperBE32 commented on Source/Sonic Frontiers/Libraries/PlayerVisual.hmm
> +    [StructLayout(LayoutKind.Explicit, Size = 0x11C /* ? */)]
`app::player::VisualSuperSonic` appears to be `0x130` in size.

2023-11-18 00:17 UTC, NM-20 commented on Source/Sonic Frontiers/Libraries/PlayerVisual.hmm
> +    [StructLayout(LayoutKind.Explicit, Size = 0x11C /* ? */)]
Is there an allocation with that size? Couldn't seem to find one myself.

2023-11-18 00:21 UTC, NM-20 commented on Source/Sonic Frontiers/Libraries/GOComponents.hmm
> +        public T *GetVisualAs<T>() where T : unmanaged
> The fact that this function pointer exists also suggests this class likely contains a MoveArray of some kind, so it might be worth mapping that instead, but I'll allow it for this PR.

What describes a `MoveArray`?

2023-11-18 02:36 UTC, HyperBE32 commented on Source/Sonic Frontiers/Libraries/PlayerVisual.hmm
> +    [StructLayout(LayoutKind.Explicit, Size = 0x11C /* ? */)]
The allocation happens in the subroutine at `0x14AE0C630`.

2023-11-18 02:37 UTC, HyperBE32 commented on Source/Sonic Frontiers/Libraries/GOComponents.hmm
> +        public T *GetVisualAs<T>() where T : unmanaged
`MoveArray<T>` can be spotted in memory like the following;

```cs
struct MoveArray<T>
{
    T* pBuffer;
    int Length;
    int Capacity;
    IAllocator* pAllocator;
}
```

If the length and capacity are 64-bit, that'll be an `ObjectMoveArray<T>` instead.

2023-11-19 02:27 UTC, NM-20 commented on Source/Sonic Frontiers/Libraries/GOComponents.hmm
> +        public T *GetVisualAs<T>() where T : unmanaged
> `MoveArray<T>` can be spotted in memory like the following;
> 
> ```cs
> struct MoveArray<T>
> {
>     T* pBuffer;
>     int Length;
>     int Capacity;
>     IAllocator* pAllocator;
> }
> ```
> 
> If the length and capacity are 64-bit, that'll be an `ObjectMoveArray<T>` instead.
> 
> You can access both of these types via the `Collections` library, I'd recommend using `#import` for easier access.

There doesn't appear to be a `MoveArray` given that information. The pointer to the PlayerVisual begins at 0x108 of `GOCPlayerVisual`.

![image](https://github.com/hedge-dev/HMMCodes/assets/35472796/9cb3b4b6-4124-4f2c-9247-bedfe440c0a3)

The function pointer is described by the following pseudocode:

![image](https://github.com/hedge-dev/HMMCodes/assets/35472796/2172e468-1d2e-4273-b8b2-db7d826a568f)

2023-11-19 02:54 UTC, HyperBE32 commented on Source/Sonic Frontiers/Libraries/GOComponents.hmm
> +        public T *GetVisualAs<T>() where T : unmanaged
My mistake, it does appear to just be a single instance then, going by that psuedocode. I'd say reimplement it as suggested anyway, rather than using a function pointer.

2023-11-19 03:16 UTC, NM-20 commented on Source/Sonic Frontiers/Libraries/GOComponents.hmm
> +        public T *GetVisualAs<T>() where T : unmanaged
> Rename to `GetVisual` and create a separate implementation that returns `PlayerVisual.Data*` with an argument for the name of the visual, using the `MAKE_GENERIC_API` macro for the templated version.
> 
> For example;
> 
> ```cs
> public PlayerVisual.Data* GetVisual(string in_visualName)
> {
>     fixed (GOCPlayerVisual* pThis = &this)
>     {
>         return GET_FUNCTION_PTR(fpInternalGetVisualAs)(pThis, StringMapOperation.ComputeHash(in_visualName));
>     }
> }
> 
> MAKE_GENERIC_API(GetVisual)
> ```
> 
> The fact that this function pointer exists also suggests this class likely contains a `MoveArray` of some kind, so it might be worth mapping that instead, but I'll allow it for this PR.

Wouldn't it make more sense to make `GetVisual` simply return `pPlayerVisual`? From there, you could have `GetVisualAs` with two overloads: one that accepts the type name as a string (private), and one that accepts a generic argument for the type (public) through the `MAKE_GENERIC_API` macro.

Having the `in_visualName` parameter in a function named `GetVisual` doesn't really clarify the parameter's purpose. The most you're getting out of it is the type safety from the name hash comparisons, since the function ends up returning a base `PlayerVisual` that has to be casted anyways.

2023-11-19 03:33 UTC, NM-20 commented on Source/Sonic Frontiers/Libraries/GOComponents.hmm
> +        public T *GetVisualAs<T>() where T : unmanaged
Also, I'm thinking of renaming the library to PlayerVisuals, then renaming the `Data` class in it to simply `PlayerVisual`. I feel like the whole `Data` layout is best suited for things like singletons. What are your thoughts?

2023-11-19 03:36 UTC, NM-20 commented on Source/Sonic Frontiers/Libraries/GOComponents.hmm
> +        public T *GetVisualAs<T>() where T : unmanaged
And yeah, I'm going to just reimplement the function in C#; no point using a signature and function pointer when it's a straightforward function.

2023-11-19 03:39 UTC, HyperBE32 commented on Source/Sonic Frontiers/Libraries/GOComponents.hmm
> +        public T *GetVisualAs<T>() where T : unmanaged
> Wouldn't it make more sense to make GetVisual simply return pPlayerVisual?

Yes.

> The most you're getting out of it is the type safety from the name hash comparisons

A lot of the time with codes, you're generally waiting for something to exist with a null check, so if you specifically need a type that isn't mapped in the `PlayerVisual` library, you can get it by name instead. If the user wants the current instance, they can just refer to the pointer, rather than calling `GetVisual`.

To be clear, the preferred code would be as follows;

```cs
public PlayerVisual.Data* GetVisual(string in_visualName)
{
    if (pPlayerVisual->GetNameHash()() == StringMapOperation.ComputeHash(in_visualName))
        return pPlayerVisual;

    return null;
}

MAKE_GENERIC_API(GetVisual)
```

And usage would be something like this for the non-templated function;

```cs
var pVisualAmy = pGOCPlayerVisual->GetVisual("VisualAmy");

if (pVisualAmy == null)
    return;

// use pVisualAmy here...
```

This isn't uncommon implementation within the libraries already, `MAKE_GENERIC_API` was made essentially so you can wait for an instance to exist so you can poke around fields manually with relative offsets, if you know what they are before they've been mapped in a library.

2023-11-19 03:43 UTC, HyperBE32 commented on Source/Sonic Frontiers/Libraries/GOComponents.hmm
> +        public T *GetVisualAs<T>() where T : unmanaged
> Also, I'm thinking of renaming the library to PlayerVisuals, then renaming the `Data` class in it to simply `PlayerVisual`. I feel like the whole `Data` layout is best suited for things like singletons. What are your thoughts?

Sounds good to me.

2023-11-19 04:46 UTC, HyperBE32 approved these changes
LGTM

2023-11-19 04:46 UTC, merged